### PR TITLE
29 autonorm config generator

### LINKED ISSUE #1: Auto-normalization config file generator for imaging
> This is a duplicate user story listed in here https://code.ornl.gov/sns-hfir-scse/imaging/imaging/-/issues/29

All the features requested as part of this user story have already been implemented in a notebook (https://neutronimaging.pages.ornl.gov/tutorial/notebooks/normalization_with_simplify_selection/#activate-search). But right now the functionality is within the main class/UI code and will need to be moved out of the script to be able to be called from the command line.
The program will take a folder or a list of folders as input. Then the program will group those data in a dictionary by folder (top level), then by acquisition duration time, then by config. Each config should have a given set of metadata. Then the acquisition starting time should also be recorded in the dictionary. The first and last image of each config will be recorded as well. Then open beam, and dark field files, found in 2 other locations, will be associated with the proper samples.

### PR DESCRIPTION
**Pull request by KedoKudo**
The following features have been implemented in this PR

- a new module, `preprocess` is added to provide the function `generate_config_CG1D` that can take a single directory or a list of directory to generate the configuration file.
- a new module, `npmath` is added to provide auxiliary function for other main modules.
- a new CLI, `generate_config.py` is added to provide CLI for the function `generate_config_CG1D`.
- corresponding documentation is updated to include instructions on how to use the newly added feature.

> closes #1

### CODE REVIEW

**Comment by JeanBilheux** [comment]
I installed the package and ran the unit tests and they all passed. But I had the following error when trying to use it
```
$python scripts/generate_config.py ~/IPTS/IPTS-25967/raw/radiographs/Aug25_2020/ ~/Desktop/
Parsing input
Traceback (most recent call last):
  File "scripts/generate_config.py", line 31, in <module>
    generate_config_CG1D(rootdir, output=output, tolerance_aperature=tor)
  File "/Users/j35/git/NeutronImagingScripts/neutronimaging/preprocess.py", line 133, in generate_config_CG1D
    raise NotImplementedError
NotImplementedError
```

**Comment by JeanBilheux** [comment]
It works when using the notebook you created. 

Question regarding the format of the json. What is the '0' in the list of df, ob? Is it an increment number for each file? I think a simple list of df, or ob files should be good enough, something like  **list_df: [{'file_1','time':4545}, {'file_2': ....} }**
Screen_Shot_2020-10-29_at_7_34_58_AM

**Comment by JeanBilheux** [comment]
I love the display JSON feature you showed me but unfortunately, it does not seem to work on chrome for me (mac). :-(. I had to use pprint instead (not as cool but does the job)

**Comment by KedoKudo** [comment]
> I installed the package and ran the unit tests and they all passed. But I had the following error when trying to use it
> 
> ```
> $python scripts/generate_config.py ~/IPTS/IPTS-25967/raw/radiographs/Aug25_2020/ ~/Desktop/
> Parsing input
> Traceback (most recent call last):
>   File "scripts/generate_config.py", line 31, in <module>
>     generate_config_CG1D(rootdir, output=output, tolerance_aperature=tor)
>   File "/Users/j35/git/NeutronImagingScripts/neutronimaging/preprocess.py", line 133, in generate_config_CG1D
>     raise NotImplementedError
> NotImplementedError
> ```

When using the script (CLI), you need to specify the output file name, such as `output.json` as the second argument.
If you want to process a list of directories, the current interface requires you to use comma to separate them, as shown in the readme:
```
generate_config.py IPTS-20267,IPTS-20268 IPTS-20267-20268.json
```

**Comment by bidochon** [comment]
My mistake, I thought the output was a folder, not a file name. It works!

**Comment by KedoKudo** [comment]
@JeanBilheux 
The following changes have been made to address the review feedback
- Explicit input arguments for raw images, open-beam images and dark-field images.
  - Both the module and the CLI have been updated with new interface
  - The example notebook has been updated using new interface
  - The instruction in `Readme.md` has been updated
- In the final output JSON file, the following fields no longer have a indexing number as key
  - `list_sample`
  - `list_ob`
  - `list_df`

Please let me know if there is any additional changes needed :smile:

**Comment by JeanBilheux** [comment]
the new version got tested and it works great.

comments: first try failed because the config file name provided did not have the ``.json`` extension. 

Ideal would be to let the user know that the extension is missing.

**Pull request merged**
